### ISSUE TITLE
Error compiling for a 64bit architecture (Raspbian Based)

### ISSUE THREAD

**Issue by edilcn** [Durgesh92/smart-dog-collor#1]
Hi Durgesh92.

I was doing the step-by-step  section, and it didn't worked.

I've managed to reach until the end. Then, when I try to execute the *python test_wake.py* the following error appears:

```
Traceback (most recent call last):
  File "test_wake.py", line 3, in <module>
    import durgesh_ai
  File "/home/pi/Projects/SmartCollar/smart-dog-collor/python_durgesh.ai/durgesh_ai/__init__.py", line 11, in <module>
    _c = open_dll()
  File "/home/pi/Projects/SmartCollar/smart-dog-collor/python_durgesh.ai/durgesh_ai/__init__.py", line 9, in open_dll
    return _ffi.dlopen(os.path.join(dlldir, "libdurgesh_ai.so"))
OSError: cannot load library '/home/pi/Projects/SmartCollar/smart-dog-collor/python_durgesh.ai/durgesh_ai/libdurgesh_ai.so': /home/pi/Projects/SmartCollar/smart-dog-collor/python_durgesh.ai/durgesh_ai/libdurgesh_ai.so: wrong ELF class: ELFCLASS64
```

I suspect this shared library needs to be recompiled using -m64 flag.

I tried to change it in the Makefile, however, I don't have  all the source files needed. (Something with the Kaldi)

`make: *** No rule to make target 'kaldi_recognizer.o', needed by 'libdurgesh-ai.so'.  Stop.`

**Comment by edilcn** [comment]
I realized that my Raspberry Pi 4 OS wasn't compatible with your project. To solve that, I've flashed another image (Ubuntu Server 64bit) and worked.
